# Generated by Django 3.2.8 on 2021-11-23 04:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_alter_posts_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 4, 31, 55, 503401, tzinfo=utc)),
        ),
    ]
