# Generated by Django 3.2.8 on 2022-06-25 21:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_alter_posts_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 21, 29, 15, 800621, tzinfo=utc)),
        ),
    ]
