# Generated by Django 3.2.8 on 2022-06-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211122_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='./default/default-profile-picture.jpg', upload_to='ProfilePictures'),
        ),
    ]
