# Generated by Django 3.2.8 on 2022-06-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='.DefaultPP.jpg', upload_to='ProfilePictures'),
        ),
    ]
